version: '3.9'
services:
  DB:
    image: postgres:latest
    restart: always
    container_name: Postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=goChat
    ports:
      - 5434:5432